export const MINEIRART_REGION_URL = "https://mineirart.com.br/regiao-dos-lagos/";
export const MINEIRART_REGION_CAPTURED_AT = new Date("2026-08-17T15:40:00Z");

const CATEGORY_BASE = `${MINEIRART_REGION_URL}categoria-produto/`;

type MineirartCategory = {
  slug: string;
  name: string;
  categoryType: "FURNITURE" | "LIGHTING" | "DECOR" | "STRUCTURE" | "TEXTILE" | "ACCESSORY" | "OTHER";
  listedProductCount: number;
  productNames: string[];
  extractionStatus: "COMPLETE_NAMES" | "PARTIAL_NAMES" | "CATEGORY_ONLY";
  notes?: string;
};

export const MINEIRART_REGION_CATALOG: MineirartCategory[] = [
  {
    slug: "almofadas",
    name: "Almofadas",
    categoryType: "TEXTILE",
    listedProductCount: 20,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Conjunto Almofada Bege (Detalhe em Couro Marrom) – 0,45 x 0,45",
      "Almofada Azul 0,45 x 0,45m",
      "Almofada Verde 0,45 x 0,45m",
      "Almofada Amarela 0,45 x 0,45m",
      "Almofada Vermelha 0,45 x 0,45m",
      "Almofada Aquablock Azul 0,45 x 0,45m",
      "Almofada Floral Laranja – 0,45 x 0,45m",
      "Almofada Azul Listras Grossas – 0,45 x 0,45m",
      "Almofada Listrada – 0,45 x 0,45m",
      "Almofada Coral Pele de Pêssego – 0,45 x 0,45m",
      "Almofada Aquablock Azul Marinho – 0,50 x 0,30m",
      "Almofada Aquablock Verde – 0,50 x 0,30m",
      "Almofada Aquablock Verde – 0,50 x 0,50m",
      "Almofada Aquablock Laranja – 0,50 x 0,30m",
      "Almofada Aquablock Laranja Mar – 0,50 x 0,30m",
      "Almofada Aquablock Laranja Mar – 0,45 x 0,45m",
      "Almofada Aquablock Azul Mar – 0,50 x 0,30m",
      "Almofada Aquablock Azul Mar – 0,45 x 0,45m",
      "Almofada Mosaico Azul – 0,45 x 0,45m",
      "Almofada Verde Pele de Pêssego – 0,45 x 0,45m",
    ],
    notes: "Acessório têxtil; não deve ser tratado como móvel.",
  },
  {
    slug: "aparadores",
    name: "Aparadores",
    categoryType: "FURNITURE",
    listedProductCount: 27,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Aparador Apollo", "Aparador Luz", "Aparador Sevilha", "Mesa Atenas P", "Aparador Utilitário Lagos",
      "Aparador Império Branco", "Aparador Tronco Celta", "Aparador Laguna Lagos", "Aparador Tronco Pranchão",
      "Aparador Demolição Gavetão", "Aparador com Tampo de Porta Antiga", "Aparador Império",
      "Aparador Demolição com Prateleira", "Aparador Napoli", "Aparador Rústico em Pátina",
      "Aparador Prateleira com Tampo de Porta Antiga", "Fruteira Alta", "Aparador Ásia",
    ],
  },
  {
    slug: "arcos-gazebos-e-portas-cerimonia",
    name: "Arcos, Gazebos e Portas/Cerimônia",
    categoryType: "STRUCTURE",
    listedProductCount: 19,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Arco Meia Lua com Extensão", "Gazebo Mahal", "Gazebo Simples para Mesa", "Gazebo Duplo para Mesa",
      "Arco Hexagonal", "Arco Lua", "Arco Meia Lua de Ferro Dourado", "Portal Triangular", "Portal Coração",
      "Arco de Cerimônia", "Portal Cerimonial Retangular", "Pergolado/Gazebo de Ferro", "Portal Cerimonial",
      "Portal para Cerimônia", "Porta em Pátina", "Varal", "Porta de Cerimônia Florence", "Arco Duplo Cerimonial", "Arco Cerimonial",
    ],
    notes: "Estruturas de cerimônia e ambientação; não são mobiliário convencional.",
  },
  {
    slug: "artigos-decorativos",
    name: "Artigos Decorativos",
    categoryType: "DECOR",
    listedProductCount: 41,
    extractionStatus: "CATEGORY_ONLY",
    productNames: [],
    notes: "A página retornou apenas códigos 2028 e 2025 com aviso de foto ilustrativa; nomes individuais pendentes.",
  },
  {
    slug: "bancos",
    name: "Bancos",
    categoryType: "FURNITURE",
    listedProductCount: 42,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Seat Garden Outdoor", "Balanço Suspenso Azul Naval", "Seat Garden X", "Seat Garden Pequim", "Banco Harpa",
      "Banco Tronco Trançado", "Banco Cielly", "Seat Garden Cinza", "Seat Garden Preto", "Banco Anel",
      "Mesa de Centro Modular Unitário", "Seat Garden Ferro Trançado", "Seat Garden Straw", "Banco Volpi",
      "Seat Garden Ferro Dourado", "Banco Ásia", "Namoradeira Viviam", "Espreguiçadeira Wave",
      "Seat Garden Ferro Coimbra", "Seat Garden Ferro Azul", "Seat Garden Ferro Grande Saúde", "Seat Garden Azul",
      "Deck", "Banco Milano", "Banco Bandeira",
    ],
    notes: "A categoria mistura bancos, assentos, namoradeira, balanço, espreguiçadeira e um deck.",
  },
  {
    slug: "banquetas",
    name: "Banquetas",
    categoryType: "FURNITURE",
    listedProductCount: 18,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Banqueta Patagônia", "Banqueta Ravenna", "Banqueta Axial", "Banqueta Cross Natural", "Banqueta de Ferro e Madeira",
      "Banqueta de Ferro com Assento de Madeira", "Mesa Comunitária Ferro + Madeira", "Banqueta Búzios",
      "Banqueta Santa Teresa", "Banqueta Itaipava", "Bistrô em Ferro com Tampo Demolição", "Banqueta Pub",
      "Mesa Comunitária", "Banqueta Mineira", "Banqueta Rio Antigo",
    ],
    notes: "A página também repete mesas comunitárias e um bistrô como itens relacionados.",
  },
  {
    slug: "barcos-e-artigos-termicos",
    name: "Barcos e Artigos Térmicos",
    categoryType: "ACCESSORY",
    listedProductCount: 2,
    extractionStatus: "CATEGORY_ONLY",
    productNames: [],
    notes: "Categoria publicada, mas os nomes individuais não foram expostos na extração textual.",
  },
  {
    slug: "bares",
    name: "Bares",
    categoryType: "FURNITURE",
    listedProductCount: 19,
    extractionStatus: "PARTIAL_NAMES",
    productNames: [],
    notes: "A página apresentou código 0314 e aviso de foto ilustrativa, mas não revelou nomes legíveis.",
  },
  {
    slug: "biombos",
    name: "Biombos",
    categoryType: "STRUCTURE",
    listedProductCount: 4,
    extractionStatus: "COMPLETE_NAMES",
    productNames: ["Placa Divisória", "Biombo de Ferro e Bambu", "Biombo em Junco", "Biombo de Ferro e Bambú"],
  },
  {
    slug: "bistros",
    name: "Bistrôs",
    categoryType: "FURNITURE",
    listedProductCount: 27,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Bistrô Alto Palm", "Bistrô Baixo Zuli", "Bistrô Alto Carioca", "Bistrô Baixo Marrocos", "Bistrô Alto Marrocos",
      "Mesa Ripada Bistrô Baixo", "Bistrô Baixo X Natural", "Bistrô Baixo de Ferro", "Bistrô Rio Antigo",
      "Bistrô Alto", "Bistrô Baixo", "Mesa Comunitária de Ferro com Tampo de Madeira", "Bistrô de Ferro com Tampo de Madeira",
      "Mesa Comunitária Comuna Natural", "Bistrô Búzios", "Bistrô de Ferro Preto", "Bistrô de Ferro Branco",
      "Bistrô de Ferro Vermelho", "Bistrô de Ferro Verde", "Bistrô de Ferro Azul", "Bistrô de Ferro Amarelo",
      "Bistrô Mineiro em Junco", "Bistrô Rio Antigo com Tampo Demolição", "Bistrô Rio Antigo Branco", "Bistrô Mineiro Tampo Demolição",
    ],
  },
  {
    slug: "cadeiras",
    name: "Cadeiras",
    categoryType: "FURNITURE",
    listedProductCount: 50,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Cadeira Esmeralda", "Cadeira Zara", "Cadeira Medalhão", "Cadeira Dobrável", "Cadeira Rio Antigo",
      "Cadeira Cross", "Cadeira Teatro", "Jogo Jardim Antigo", "Cadeira Búzios", "Cadeira Santa Teresa",
      "Cadeira Santa Teresa Junco", "Cadeira Austríaca", "Cadeira Thonet", "Cadeira Prada Tiffany Castanho",
      "Cadeira Bellagio", "Cadeira Prada Tiffany de Bambu", "Cadeira Ásia com Braço",
    ],
    notes: "As variações por cor, rattan, palhinha, linho, veludo, bambu e estofado foram consolidadas por modelo.",
  },
  {
    slug: "carrinhos",
    name: "Carrinhos",
    categoryType: "FURNITURE",
    listedProductCount: 3,
    extractionStatus: "COMPLETE_NAMES",
    productNames: ["Baú Rústico", "Carrinho de Bar/Doce Castanho", "Carrinho Expositor"],
  },
  {
    slug: "decks",
    name: "Decks",
    categoryType: "STRUCTURE",
    listedProductCount: 1,
    extractionStatus: "COMPLETE_NAMES",
    productNames: ["Deck – 2,00 x 1,00 x 0,10m"],
    notes: "Estrutura/piso de ambientação, não móvel.",
  },
  {
    slug: "diversos",
    name: "Diversos",
    categoryType: "OTHER",
    listedProductCount: 3,
    extractionStatus: "CATEGORY_ONLY",
    productNames: [],
    notes: "A página não permitiu extração textual.",
  },
  {
    slug: "estantes",
    name: "Estantes",
    categoryType: "FURNITURE",
    listedProductCount: 14,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Estante Divisória", "Estante Marrocos", "Estante Grécia", "Estante Versátil", "Estante Triângulo", "Estante Ouro",
      "Móvel Utilitário", "Estante de Ferro Lisboa", "Estante de Ferro Preta com Rodinha", "Estante Expositora Natural",
      "Estante Mineira Rústica", "Estante Rústica Império", "Armário Rústico Império", "Estante Vazada",
    ],
  },
  {
    slug: "luminarias",
    name: "Luminárias",
    categoryType: "LIGHTING",
    listedProductCount: 59,
    extractionStatus: "PARTIAL_NAMES",
    productNames: [
      "Bocal + 1,50m de fio + lâmpada de filamento (códigos 7991, 7931, 7930, 5299, 5298, 7946, 7939–7910)",
      "Luminária com cabo de aço 1,70m (cód. 8692)",
    ],
    notes: "A página informa que a Mineirart não realiza instalação; itens são iluminação técnica, não móveis.",
  },
  {
    slug: "mesas-de-centro-lateral",
    name: "Mesas de Centro/Lateral",
    categoryType: "FURNITURE",
    listedProductCount: 61,
    extractionStatus: "PARTIAL_NAMES",
    productNames: ["Mesa Lateral Serena", "Conjunto de Mesas código 5020", "Conjunto de Mesas código 4848"],
    notes: "A página revela medidas e códigos, mas não todos os nomes; itens sem nome ficaram pendentes.",
  },
  {
    slug: "mesas-para-bolo",
    name: "Mesas para Bolo",
    categoryType: "FURNITURE",
    listedProductCount: 34,
    extractionStatus: "PARTIAL_NAMES",
    productNames: [],
    notes: "A extração retornou códigos 1051, 7922 e 5598, mas não nomes legíveis.",
  },
  {
    slug: "mesas-para-convidados",
    name: "Mesas para Convidados",
    categoryType: "FURNITURE",
    listedProductCount: 88,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Mesa Mol com Tampo Demolição", "Mesa Rústica Família", "Mesa Búzios", "Mesa de Ferro com Tampo de Madeira",
      "Mesa Rústica Demolição Duas Gavetas", "Mesa Cancun", "Mesa Pérgula", "Mesa Laguna Lagos", "Mesa Tronco Harpa",
      "Mesa Coroa Alta Lagos", "Mesa Tronco Espiral", "Mesa Tronco Pé", "Mesa Traço", "Móvel Utilitário",
      "Mesa Utilitária", "Mesa Bistrô Coimbra", "Mesa Comunitária Ferro + Madeira", "Jogo Jardim Antigo",
      "Mesa Suspensa Lagos", "Mesa de Botequim Mosaico Kaiser", "Mesa de Ferro com Tampo de Vidro", "Mesa Lateral Búzios",
      "Mesa Ampulheta", "Mesa Lateral Straw", "Mesa Tulipa", "Mesa Twister",
    ],
    notes: "A página apresenta 88 anúncios; nomes e variações foram consolidados sem apagar códigos/medidas da fonte.",
  },
  {
    slug: "ombrelones",
    name: "Ombrelones",
    categoryType: "STRUCTURE",
    listedProductCount: 1,
    extractionStatus: "COMPLETE_NAMES",
    productNames: ["Ombrelone com Base para Mesa – Ø 2,40m"],
    notes: "Cobertura/ambientação externa, não móvel convencional.",
  },
  {
    slug: "poltronas",
    name: "Poltronas",
    categoryType: "FURNITURE",
    listedProductCount: 24,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Poltrona Luma", "Poltrona Lira", "Poltrona Solana", "Puff Poltrona Cati", "Poltrona Cloé/Cleo", "Poltrona Moscou",
      "Poltrona Arco Jade", "Poltrona California", "Balanço Suspenso Azul Naval", "Poltrona Cleo", "Poltrona Rasa",
      "Poltrona Geribá", "Poltrona Vime Light", "Poltrona Balanço Vime Light", "Poltrona Maximus", "Poltrona Flora",
      "Poltrona Santa Teresa", "Poltrona Traço", "Poltrona Veneza", "Poltrona Vivian", "Poltrona Napoli", "Cadeira Ásia com Braço",
    ],
    notes: "Puffs, balanço e cadeira reaparecem em categorias cruzadas e serão tratados como subtipos, não duplicatas.",
  },
  {
    slug: "puffs",
    name: "Puffs",
    categoryType: "FURNITURE",
    listedProductCount: 23,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Puff Patagônia", "Puff Gomos", "Puff Alba", "Puff Poltrona Cati", "Puff Unique", "Puff Reale", "Puff Vintage",
      "Puff Rasa", "Puff Napoli", "Puff Lilás", "Puff Vermelho", "Seat Garden Búzios", "Seat Garden Nest", "Banco Volpi",
      "Puff Napoli Ilha", "Puff Junco", "Puff Ásia",
    ],
    notes: "Seat gardens e bancos reaparecem na categoria; preservar o nome publicado e registrar a sobreposição em nota.",
  },
  {
    slug: "sofas",
    name: "Sofás",
    categoryType: "FURNITURE",
    listedProductCount: 37,
    extractionStatus: "PARTIAL_NAMES",
    productNames: ["Sofá Serena"],
    notes: "A página da categoria retornou apenas código 1453; Sofá Serena foi confirmado na página principal e em referência de produto.",
  },
  {
    slug: "sousplats",
    name: "Sousplats",
    categoryType: "ACCESSORY",
    listedProductCount: 1,
    extractionStatus: "COMPLETE_NAMES",
    productNames: ["Sousplat Rattan – Ø 0,32m"],
    notes: "Acessório de mesa, não móvel.",
  },
  {
    slug: "tapetes",
    name: "Tapetes",
    categoryType: "TEXTILE",
    listedProductCount: 40,
    extractionStatus: "COMPLETE_NAMES",
    productNames: [
      "Tapete Egípcio Sisal Marfim", "Tapete Turco Creme", "Tapete Belga Bege Escuro", "Tapete Rincon Cinza",
      "Tapete Belga Vênus Trad", "Tapete Losan Bege", "Tapete Egípcio Ecenze Greece", "Tapete Belga Lana Bege",
      "Tapete Turco Artistic Bege Claro", "Tapete Multicolor", "Tapete Sisal Ilhéus", "Tapete Sisal Zig", "Tapete Diamond Cinza",
      "Tapete Sisal Santana", "Tapete Innove", "Tapete Belga Marrom", "Tapete Passadeira Belga Stillo", "Tapete La Rochelle Azul",
      "Tapete Dakar Marinho", "Tapete Belga Stillo Vermelho e Branco", "Tapete Stillo Bege e Preto", "Tapete Ávila",
      "Tapete Anand Preto", "Tapete Dakar Preto", "Tapete Passadeira Patan Preta", "Tapete Passadeira Patan Bege",
      "Tapete Antep Laranja", "Tapete Antep Azul", "Tapete Sisal Fortaleza", "Tapete Passadeira Belga", "Tapete Passadeira Bege Listrada",
      "Tapete Passadeira Salute", "Tapete Multicor", "Tapete Marinho", "Tapete Chocolate", "Tapete Belga Nativo", "Tapete Belga",
      "Tapete Vermelho", "Tapete Preto",
    ],
    notes: "Têxteis de ambientação; não devem ser tratados como móveis.",
  },
];

export function toMineirartCategoryCreateData(supplierId: string, tenantId: string, organizationId: string) {
  return MINEIRART_REGION_CATALOG.map((category) => ({
    tenantId,
    organizationId,
    supplierId,
    slug: category.slug,
    name: category.name,
    categoryType: category.categoryType,
    listedProductCount: category.listedProductCount,
    sourceUrl: `${CATEGORY_BASE}${category.slug}/`,
    productNames: category.productNames,
    extractionStatus: category.extractionStatus,
    notes: category.notes,
    sourceCapturedAt: MINEIRART_REGION_CAPTURED_AT,
  }));
}
