export type SupplierResearchSeed = {
  name: string;
  category: "CATERING" | "FURNITURE_RENTAL" | "OTHER";
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  instagramUrl?: string | null;
  serviceArea: string[];
  sourceUrl: string;
  validationLevel: "A" | "B" | "C";
  contactStatus: "CONFIRMED_OFFICIAL" | "CONFIRMED_PUBLIC" | "NOT_FOUND_PUBLIC";
  services: string[];
  notes: string;
};

export const REGIONAL_BUFFET_DECOR_SUPPLIERS: SupplierResearchSeed[] = [
  {
    name: "Passalini Buffet",
    category: "CATERING",
    phone: "(22) 99874-1384 / (22) 2644-7005",
    email: "contato@passalinibuffet.com.br",
    website: "https://www.passalinibuffet.com.br/",
    serviceArea: ["Cabo Frio", "Búzios", "São Pedro da Aldeia", "Araruama", "Saquarema", "Região dos Lagos"],
    sourceUrl: "https://www.passalinibuffet.com.br/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["buffet", "alta gastronomia", "ilhas temáticas", "mesa de frios", "finger food", "japonês", "paella", "cardápio personalizado"],
    notes: "Oferta de buffet para casamentos confirmada no site oficial; a cobertura exata por venue deve ser cotada.",
  },
  {
    name: "Captain's Buffet",
    category: "CATERING",
    phone: "(22) 99965-3499",
    website: "https://www.captainsbuffet.com.br/",
    instagramUrl: "https://www.instagram.com/captainsbuffetbuzios/",
    serviceArea: ["Armação dos Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.captainsbuffet.com.br/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["buffet para casamentos", "buffet social", "buffet corporativo", "gastronomia costeira"],
    notes: "O site oficial está em construção, mas declara buffet para casamentos e disponibiliza WhatsApp; menu e capacidade devem ser confirmados.",
  },
  {
    name: "Luis Buffet",
    category: "CATERING",
    serviceArea: ["Araruama", "Saquarema", "Cabo Frio", "Búzios", "Rio Bonito"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/luis-buffet--e86314",
    validationLevel: "A",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["alimentação", "bebidas", "bolo", "doces", "bem-casados", "open bar", "iluminação", "decoração", "mobiliário", "cerimonial"],
    notes: "A ficha especializada atualizada em agosto de 2026 declara atendimento regional e serviço integrado; não foi encontrado contato direto público na fonte consultada.",
  },
  {
    name: "Mansão das Orquídeas",
    category: "CATERING",
    phone: "(22) 98821-5740",
    email: "mansaodasorquideas.araruama@gmail.com",
    website: "https://mansaodasorquideas.com.br/",
    serviceArea: ["Araruama"],
    sourceUrl: "https://mansaodasorquideas.com.br/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["buffet próprio", "decoração exclusiva", "discoteca", "pacotes completos", "gerador"],
    notes: "O site informa atendimento máximo de 200 convidados, buffet próprio, decoração exclusiva e gerador.",
  },
  {
    name: "Carla Valéria Festas",
    category: "CATERING",
    serviceArea: ["Cabo Frio", "Arraial do Cabo", "Região dos Lagos"],
    sourceUrl: "https://www.facebook.com/carlavaleriafestas/",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "coffee break", "decoração", "casamentos"],
    notes: "Perfil público e publicação de casamento no Pontal da Grécia, em Arraial do Cabo; contato direto deve ser confirmado no perfil.",
  },
  {
    name: "Léa Buffet",
    category: "CATERING",
    serviceArea: ["Cabo Frio", "Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.instagram.com/lea_buffet/",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "casamentos", "eventos sociais"],
    notes: "Perfil público declara atuação regional e mais de 3.000 eventos; capacidade e contato comercial devem ser confirmados.",
  },
  {
    name: "Buffet Lagos",
    category: "CATERING",
    phone: "(22) 98150-5715",
    website: "https://www.facebook.com/buffetlagoss/",
    serviceArea: ["Cabo Frio", "Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/buffet-lagos--e123938",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["buffet", "decoração", "casamentos"],
    notes: "Diretório especializado e perfil público indicam buffet e decoração; valor publicado em rede social deve ser tratado apenas como referência histórica.",
  },
  {
    name: "RSBuffet",
    category: "CATERING",
    serviceArea: ["Arraial do Cabo"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/rio-de-janeiro/arraial-do-cabo",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "serviço de mesa", "casamentos"],
    notes: "Fornecedor listado no diretório de Arraial do Cabo; contato, portfólio e disponibilidade devem ser confirmados.",
  },
  {
    name: "D'Art Buffet",
    category: "CATERING",
    serviceArea: ["São Pedro da Aldeia", "Araruama"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/dart-buffet--e148456",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "decoração integrada", "casamentos"],
    notes: "Diretório indica integração entre buffet e decoração; validar estrutura operacional e atendimento ao venue.",
  },
  {
    name: "BBQ My House",
    category: "CATERING",
    serviceArea: ["São Pedro da Aldeia", "Região dos Lagos"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/bbq-my-house--e261295",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet de churrasco", "casamentos", "eventos sociais"],
    notes: "Opção especializada em churrasco; confirmar cozinha, equipe e logística para venues externos.",
  },
  {
    name: "Samantha Laurindo Gastronomia",
    category: "CATERING",
    serviceArea: ["Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/samantha-laurindo-gastronomia--e171234",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["gastronomia", "buffet", "casamentos", "experiência personalizada"],
    notes: "Diretório e perfil profissional indicam atendimento personalizado; confirmar se oferece buffet completo ou catering parcial.",
  },
  {
    name: "La Cuisine de Michele Marucco",
    category: "CATERING",
    serviceArea: ["Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/la-cuisine-de-michele-marucco--e127524",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["alta gastronomia", "catering", "cozinha francesa", "frutos do mar"],
    notes: "Opção premium de Búzios; confirmar deslocamento, formato de serviço e capacidade para o espaço escolhido.",
  },
  {
    name: "Restaurante e Catering Cigalon",
    category: "CATERING",
    serviceArea: ["Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/buffet-casamento/restaurante-e-catering-cigalon--e79157",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["catering", "cozinha francesa", "frutos do mar", "casamentos"],
    notes: "Fornecedor de catering listado para Búzios; confirmar atendimento fora do restaurante e estrutura de evento externo.",
  },
  {
    name: "Babi Decor",
    category: "OTHER",
    phone: "(22) 99860-2077",
    email: "contato@babidecor.com.br",
    website: "https://babidecor.com.br/",
    instagramUrl: "https://www.instagram.com/babidecorfest/",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://babidecor.com.br/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["decoração de casamentos", "curadoria de peças", "locação", "destination weddings"],
    notes: "Site oficial apresenta páginas de casamentos e aluguel; confirmar municípios, montagem e desmontagem para cada venue.",
  },
  {
    name: "Bel Festas e Eventos",
    category: "OTHER",
    serviceArea: ["Armação dos Búzios", "Cabo Frio", "Arraial do Cabo"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/bel-festas-e-eventos--e361040",
    validationLevel: "A",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["decoração", "locação", "casamento pé na areia", "elopement", "mini wedding"],
    notes: "Perfil oficial declara atuação em Búzios, Cabo Frio e Arraial do Cabo; contato deve ser obtido no perfil oficial.",
  },
  {
    name: "Móveis do Portinho",
    category: "FURNITURE_RENTAL",
    phone: "(22) 99914-0359",
    email: "moveisdoportinho@gmail.com",
    website: "http://moveisdoportinho.com.br/produtos.php",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "http://moveisdoportinho.com.br/produtos.php",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["locação de móveis", "aparadores", "mesas", "cadeiras", "sofás", "puffs", "gazebos", "portais", "decks", "sousplats"],
    notes: "Site oficial publica catálogo extenso e preços de referência; confirmar disponibilidade, transporte e montagem.",
  },
  {
    name: "Mineirart — Região dos Lagos",
    category: "FURNITURE_RENTAL",
    serviceArea: ["Cabo Frio", "Búzios", "Arraial do Cabo", "Araruama", "São Pedro da Aldeia", "Saquarema", "Região dos Lagos"],
    sourceUrl: "https://mineirart.com.br/regiao-dos-lagos/",
    validationLevel: "A",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["locação de móveis", "decoração", "ambientação", "estruturas", "iluminação", "têxteis"],
    notes: "Fornecedor regional já cadastrado com inventário de 25 categorias; contatos devem ser confirmados na unidade Região dos Lagos.",
  },
  {
    name: "Dona Branca Locações",
    category: "FURNITURE_RENTAL",
    phone: "(22) 99945-2955",
    instagramUrl: "https://www.instagram.com/donabrancalocacao/",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://www.facebook.com/donabrancalocacoes/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["locação de artigos", "mesas", "louças", "mobiliário", "decoração de casamentos"],
    notes: "Perfil público informa loja em São Cristóvão, Cabo Frio, e atuação regional; confirmar entrega, montagem e disponibilidade.",
  },
  {
    name: "Neusa Festas",
    category: "FURNITURE_RENTAL",
    phone: "(22) 97401-6389",
    email: "festasneusa@gmail.com",
    instagramUrl: "https://www.instagram.com/neusafestas/",
    serviceArea: ["Cabo Frio"],
    sourceUrl: "https://nlocacao.estoquenow.site/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["locação de mesas", "mesa posta", "bandejas", "toalhas", "tapetes", "vasos", "sousplats"],
    notes: "Catálogo público identifica a operação em Cabo Frio; confirmar atendimento fora do município e montagem.",
  },
  {
    name: "Maison Blanche Weddings Planner & Decor",
    category: "OTHER",
    serviceArea: ["Cabo Frio", "Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.casamentos.com.br/cerimonialista/maison-blanche-weddings-planner-&-decor--e253869",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["wedding planner", "cerimonial", "decoração", "produção integral"],
    notes: "Posicionamento premium e atuação em casamentos; contato direto e área operacional precisam ser confirmados.",
  },
  {
    name: "Styllo's Clean Decoração",
    category: "OTHER",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/styllos-clean-decoracao--e463276",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["decoração", "mesas postas", "ambientação"],
    notes: "Diretório informa atendimento a toda a Região dos Lagos; confirmar data, equipe e montagem.",
  },
  {
    name: "Véu e Grinalda Cerimonial e Decoração",
    category: "OTHER",
    serviceArea: ["Cabo Frio"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/veu-e-grinalda-cerimonial-e-decoracao--e134857",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["cerimonial", "decoração", "produção de casamento"],
    notes: "Diretório especializado registra experiência e avaliações; confirmar atuação atual.",
  },
  {
    name: "Allameda Locações",
    category: "FURNITURE_RENTAL",
    serviceArea: ["Araruama", "Saquarema"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/allameda-locacoes--e444978",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["locação de móveis", "peças decorativas", "curadoria"],
    notes: "Fornecedor local listado para Araruama; confirmar catálogo, contato e atendimento ao venue.",
  },
  {
    name: "Lanes Buffet & Decorações",
    category: "CATERING",
    serviceArea: ["Araruama"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/lanes-buffet--e123907",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "decoração", "casamentos"],
    notes: "Fornecedor integrado listado para Araruama; confirmar capacidade, cardápio e estrutura.",
  },
  {
    name: "El Elion Buffet e Decoração",
    category: "CATERING",
    serviceArea: ["Araruama"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/el-elion-buffet-e-decoracao--e252385",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "decoração", "casamentos"],
    notes: "Fornecedor integrado listado para Araruama; confirmar contato direto e portfólio recente.",
  },
  {
    name: "MS Buffet & Decoração",
    category: "CATERING",
    serviceArea: ["São Pedro da Aldeia"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/ms-buffet-&-decoracao--e179178",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "decoração", "casamentos"],
    notes: "Fornecedor local listado para São Pedro da Aldeia; confirmar capacidade, equipe e logística.",
  },
  {
    name: "Lotus",
    category: "FURNITURE_RENTAL",
    serviceArea: ["São Pedro da Aldeia"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/lotus--e235803",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["locação de móveis", "materiais decorativos", "ambientação"],
    notes: "Diretório indica locação de móveis e materiais para casamentos; confirmar contato e catálogo.",
  },
  {
    name: "Andrezza Côrtes",
    category: "OTHER",
    serviceArea: ["Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/andrezza-cortes--e223224",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["decoração", "flores", "paisagismo", "projetos personalizados"],
    notes: "Perfil especializado em natureza, flores e paisagismo; confirmar contato, cobertura e data.",
  },
  {
    name: "Amanda Birse Design de Eventos",
    category: "OTHER",
    serviceArea: ["Armação dos Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/amanda-birse-design-de-eventos--e205532",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["design de eventos", "decoração autoral", "destination weddings"],
    notes: "Diretório informa dez anos de experiência; confirmar contato e municípios atendidos.",
  },
  {
    name: "Raquel Goulart Decor",
    category: "OTHER",
    serviceArea: ["Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/decoracao-casamento/raquel-goulart-decor--e175951",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["decoração personalizada", "eventos sociais", "eventos corporativos"],
    notes: "Fornecedor listado para Búzios; confirmar contato e portfólio recente.",
  },
  {
    name: "Se Vira nos 30 Festas",
    category: "CATERING",
    phone: "(22) 99928-3061",
    instagramUrl: "https://www.instagram.com/se_vira_nos_30_festas/",
    serviceArea: ["Cabo Frio", "Búzios", "São Pedro da Aldeia", "Araruama", "Saquarema", "Região dos Lagos"],
    sourceUrl: "https://www.instagram.com/se_vira_nos_30_festas/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["buffet", "decoração", "organização de eventos", "casamentos"],
    notes: "Perfil público declara mais de 1.800 festas realizadas e atendimento à Região dos Lagos; confirmar capacidade e formato do pacote.",
  },
  {
    name: "Fernanda Rodrigues Buffet",
    category: "CATERING",
    serviceArea: ["Saquarema", "Região dos Lagos"],
    sourceUrl: "https://www.instagram.com/fernandarodriguesbuffet/",
    validationLevel: "B",
    contactStatus: "NOT_FOUND_PUBLIC",
    services: ["buffet", "casamentos", "aniversários"],
    notes: "Perfil público declara atendimento a toda a Região dos Lagos; confirmar contato e oferta de decoração.",
  },
];
