export type PhotoVideoSupplierResearchSeed = {
  name: string;
  category: "PHOTOGRAPHY" | "OTHER";
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  instagramUrl?: string | null;
  serviceArea: string[];
  sourceUrl: string;
  validationLevel: "A" | "B" | "C";
  contactStatus: "CONFIRMED_OFFICIAL" | "CONFIRMED_PUBLIC" | "NOT_FOUND_PUBLIC";
  services: string[];
  notes: string;
};

export const REGIONAL_PHOTO_VIDEO_SUPPLIERS: PhotoVideoSupplierResearchSeed[] = [
  {
    name: "JC Fotografias — Jonathan e Crislane",
    category: "PHOTOGRAPHY",
    phone: "+55 22 99834-7828",
    website: "https://www.jcfotografias.com.br/",
    serviceArea: ["Região dos Lagos", "Cabo Frio", "Arraial do Cabo", "Armação dos Búzios"],
    sourceUrl: "https://www.jcfotografias.com.br/sobre",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento", "pré-wedding", "ensaios"],
    notes: "Fonte oficial consultada; disponibilidade, pacote, deslocamento e condições comerciais devem ser cotados para cada evento.",
  },
  {
    name: "Tatiana Almeida Photography",
    category: "PHOTOGRAPHY",
    website: "https://tatianalmeidaphotography.com/",
    serviceArea: ["Cabo Frio", "Região dos Lagos", "deslocamento nacional"],
    sourceUrl: "https://tatianalmeidaphotography.com/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia documental", "fotografia atemporal", "casamento", "destination wedding"],
    notes: "Fonte oficial consultada; contato direto, agenda, deslocamento e valores devem ser confirmados antes da proposta final.",
  },
  {
    name: "Alexandre Fontenele Fotografia",
    category: "PHOTOGRAPHY",
    website: "https://fontenelefoto.alboompro.com/",
    serviceArea: ["Armação dos Búzios", "Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://fontenelefoto.alboompro.com/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento", "fotografia de eventos"],
    notes: "Portfólio público consultado; cobertura por município, agenda, preço e logística ainda precisam de confirmação.",
  },
  {
    name: "Elis Morais Fotografia",
    category: "PHOTOGRAPHY",
    phone: "+55 22 99262-0290",
    email: "contato@elismorais.com.br",
    website: "https://www.elismorais.com.br/",
    instagramUrl: "https://www.instagram.com/elismorais.fotografia/",
    serviceArea: ["Armação dos Búzios", "Arraial do Cabo", "Cabo Frio", "Araruama"],
    sourceUrl: "https://www.elismorais.com.br/blog/casamento-a-dois",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento na praia", "elopement wedding", "destination wedding", "pré-wedding", "vídeo"],
    notes: "Site oficial informa atuação regional e contato público; disponibilidade, pacote, deslocamento e escopo de vídeo devem ser confirmados.",
  },
  {
    name: "Raquel Bastos Fotografia",
    category: "PHOTOGRAPHY",
    phone: "+55 22 99223-1958",
    email: "contato@raquelbastos.com.br",
    website: "https://raquelbastos.com.br/",
    instagramUrl: "https://www.instagram.com/raquelbastosfotografia/",
    serviceArea: ["Cabo Frio", "Armação dos Búzios", "Arraial do Cabo"],
    sourceUrl: "https://raquelbastos.com.br/portfolio_page/1-ano/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento", "elopement wedding", "destination wedding", "casamento intimista", "pré-wedding"],
    notes: "Site oficial informa fotografia de casamento e ensaios; data, pacote e taxa para outros municípios devem ser confirmados.",
  },
  {
    name: "Rafael Ribeiro Fotografia",
    category: "PHOTOGRAPHY",
    instagramUrl: "https://www.facebook.com/rafaelriberfotografia/",
    serviceArea: ["Cabo Frio", "Macaé", "Região dos Lagos"],
    sourceUrl: "https://www.facebook.com/rafaelriberfotografia/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["fotografia de casamento", "fotografia de praia", "ensaios", "destination wedding"],
    notes: "Perfil público consultado; contato, disponibilidade, valores e cobertura exata devem ser confirmados diretamente.",
  },
  {
    name: "Alexandre Duque Fotografia e Filmes",
    category: "OTHER",
    website: "https://alexandreduque.com/",
    instagramUrl: "https://www.instagram.com/alexandreduquefotografia/",
    serviceArea: ["Cabo Frio", "Armação dos Búzios", "Região dos Lagos", "Rio de Janeiro"],
    sourceUrl: "https://alexandreduque.com/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia", "filmes", "produção audiovisual", "eventos", "casamento a confirmar"],
    notes: "Site oficial descreve produção audiovisual e fotografia; pacote específico de casamento, agenda e deslocamento devem ser confirmados.",
  },
  {
    name: "Adryel William Fotógrafo",
    category: "PHOTOGRAPHY",
    website: "https://www.adryelwilliamfotografia.com.br/",
    instagramUrl: "https://www.instagram.com/adryelwilliamfotografo/",
    serviceArea: ["Araruama", "Região dos Lagos"],
    sourceUrl: "https://www.adryelwilliamfotografia.com.br/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento", "destination wedding", "mini wedding", "pré-wedding", "eventos"],
    notes: "Portfólio oficial mostra casamento em Cabo Frio e mini wedding em Araruama; agenda, preços e deslocamento devem ser cotados.",
  },
  {
    name: "João Henrique Fotografia",
    category: "PHOTOGRAPHY",
    phone: "+55 22 99927-2967",
    website: "https://www.jhfotos.com.br/",
    instagramUrl: "https://www.instagram.com/jhfotos22/",
    serviceArea: ["São Pedro da Aldeia", "Armação dos Búzios", "Região dos Lagos"],
    sourceUrl: "https://www.jhfotos.com.br/ultimos-casamentos/categoria/sao-pedro-da-aldeia",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia de casamento", "família", "ensaios", "pré-wedding"],
    notes: "Site e portfólio público indicam cobertura em São Pedro da Aldeia e Búzios; disponibilidade e deslocamento devem ser confirmados.",
  },
  {
    name: "Remember Foto e Filme",
    category: "OTHER",
    phone: "+55 21 96512-8492",
    email: "rememberfotoefilme@gmail.com",
    website: "https://rememberfotoefilme.com.br/",
    serviceArea: ["Região dos Lagos", "Araruama"],
    sourceUrl: "https://rememberfotoefilme.com.br/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["fotografia", "filmagem", "pré-wedding", "casamento"],
    notes: "Fonte oficial e contatos públicos registrados; pacote, equipe, horas de cobertura, entrega e deslocamento devem ser cotados.",
  },
  {
    name: "Passaline Films",
    category: "OTHER",
    phone: "+55 22 99922-3566",
    email: "passaline@hotmail.com",
    instagramUrl: "https://www.instagram.com/passalinefilms/",
    serviceArea: ["Cabo Frio", "Arraial do Cabo", "Região dos Lagos"],
    sourceUrl: "https://www.instagram.com/passalinefilms/",
    validationLevel: "A",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["vídeo de casamento", "filmagem de praia", "wedding film"],
    notes: "Perfil público e contatos registrados; disponibilidade, equipe, captação de áudio, drone, entrega e direitos de uso devem ser confirmados.",
  },
  {
    name: "JB Videomaker / Fotógrafo",
    category: "OTHER",
    instagramUrl: "https://www.instagram.com/jbvideomakerr/",
    serviceArea: ["Arraial do Cabo", "Cabo Frio", "Armação dos Búzios"],
    sourceUrl: "https://www.instagram.com/jbvideomakerr/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["fotografia", "wedding film", "vídeo", "narrativa cinematográfica"],
    notes: "Perfil público consultado; contato direto, agenda, pacote, equipe e deslocamento devem ser confirmados.",
  },
  {
    name: "Old Films",
    category: "OTHER",
    website: "https://www.casamentos.com.br/filmagem-casamento/old-films--e210050/videos",
    serviceArea: ["Cabo Frio", "Armação dos Búzios"],
    sourceUrl: "https://www.casamentos.com.br/filmagem-casamento/old-films--e210050/videos",
    validationLevel: "A",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["filmagem de casamentos", "wedding film"],
    notes: "Ficha especializada e vídeos públicos consultados; contato, disponibilidade, equipe e escopo devem ser confirmados.",
  },
  {
    name: "TC Produções",
    category: "OTHER",
    phone: "+55 21 99332-1108",
    website: "https://www.tcproducoes.com.br/",
    serviceArea: ["Rio de Janeiro", "Niterói", "Baixada Fluminense", "Região dos Lagos a confirmar"],
    sourceUrl: "https://www.tcproducoes.com.br/",
    validationLevel: "B",
    contactStatus: "CONFIRMED_OFFICIAL",
    services: ["foto", "vídeo", "drone", "alta resolução", "eventos"],
    notes: "Fonte oficial e contato público registrados; atendimento efetivo na Região dos Lagos, casamento e deslocamento precisam de confirmação.",
  },
  {
    name: "Mayiko Lima Filmes",
    category: "OTHER",
    instagramUrl: "https://www.instagram.com/mayikolimafilmes/",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://www.facebook.com/mayikolimafilms/?locale=pt_BR",
    validationLevel: "C",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["filmagem", "eventos", "vídeos corporativos", "wedding film a confirmar"],
    notes: "Perfil público descreve produção audiovisual em Cabo Frio; serviço específico de casamento, contato, agenda e valores devem ser confirmados.",
  },
  {
    name: "Atos Produções",
    category: "OTHER",
    instagramUrl: "https://www.instagram.com/atosproducoesoficial/",
    serviceArea: ["Cabo Frio", "Região dos Lagos"],
    sourceUrl: "https://www.instagram.com/atosproducoesoficial/",
    validationLevel: "C",
    contactStatus: "CONFIRMED_PUBLIC",
    services: ["produção de vídeo", "filmagem de eventos", "filmagem de casamento a confirmar"],
    notes: "Perfil público localizado em Cabo Frio; serviço específico de casamento, contato, agenda e pacote devem ser confirmados.",
  },
];
