export type WeddingVenueResearchSeed = {
  name: string;
  municipality: string;
  venueType: string;
  evidenceLevel: "OFFICIAL" | "DIRECTORY" | "SOCIAL_LEAD";
  status: "VALIDATED" | "REQUIRES_CONFIRMATION";
  capacityMin?: number;
  capacityMax?: number;
  lodgingCapacity?: number;
  priceNote?: string;
  services: string[];
  sourceUrls: string[];
  contact?: string;
  notes?: string;
};

export const WEDDING_VENUE_RESEARCH: WeddingVenueResearchSeed[] = [
  {
    name: "Casa de Vidro Festas",
    municipality: "Cabo Frio",
    venueType: "Casa de festas",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    services: ["casamentos", "cerimônia ao ar livre", "Casa", "Espaço Gourmet", "Boate"],
    sourceUrls: ["https://www.casadevidrofestas.com.br/"],
    contact: "Av. Henrique Terra, 81, Palmeiras, Cabo Frio/RJ · (22) 2643-5990 · (22) 2645-6882 · (21) 96416-4547 · casadevidro.orcamentos@gmail.com",
    notes: "Capacidade e preço não publicados na página inicial; confirmar diretamente.",
  },
  {
    name: "Inspiração Casa de Festas",
    municipality: "Cabo Frio",
    venueType: "Casa de festas",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    services: ["casamentos", "área verde", "jardim", "lago", "pergolado", "piscina", "suíte da noiva", "cozinha de apoio"],
    sourceUrls: ["https://inspiracaocasadefestas.com.br/"],
    contact: "Rua Cel. Ferreira, 221, Portinho, Cabo Frio/RJ · (22) 98837-6992",
    notes: "Capacidade e preço não publicados no site consultado.",
  },
  {
    name: "Casa Pôr do Sol",
    municipality: "Cabo Frio",
    venueType: "Casa com jardim e hospedagem",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    capacityMax: 150,
    lodgingCapacity: 14,
    services: ["casamentos", "eventos", "piscina", "jardim", "vista para o pôr do sol", "hospedagem"],
    sourceUrls: ["https://casapordosolcabofrio.com.br/site/"],
    contact: "Rua Luiz Feliciano Cardoso, 975, Palmeiras, Cabo Frio/RJ · (22) 99760-8097 · contato@casapordosolcabofrio.com.br",
  },
  {
    name: "Mansão do Canal",
    municipality: "Cabo Frio",
    venueType: "Mansão e casa de eventos",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    capacityMax: 250,
    priceNote: "Referência de anúncio desde R$5.000; confirmar natureza do valor.",
    services: ["cerimônia ao ar livre", "casarão colonial", "deck no canal", "cozinha completa", "suítes", "suíte da noiva"],
    sourceUrls: ["https://www.casamentos.com.br/casa-para-casamento/mansao-do-canal--e358898"],
    notes: "Informação validada em diretório especializado; preço e disponibilidade requerem contato direto.",
  },
  {
    name: "Vila da Santa Hotel Boutique & SPA",
    municipality: "Búzios",
    venueType: "Hotel boutique e destination wedding",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    lodgingCapacity: 53,
    services: ["casamento em Búzios", "exclusividade do hotel", "Casa Secreta", "Pátio Principal", "salão do restaurante", "área da piscina", "gerador", "mobiliário opcional"],
    sourceUrls: ["https://www.viladasanta.com/eventos"],
    notes: "A página informa 24 acomodações para até 53 convidados; preço não publicado.",
  },
  {
    name: "CasAmar",
    municipality: "Búzios",
    venueType: "Casa à beira-mar",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    capacityMax: 200,
    lodgingCapacity: 12,
    services: ["casamento pé na areia", "jardim", "deck", "pista de dança", "suíte nupcial", "espaço zen", "cozinha para buffet", "banheiros externos"],
    sourceUrls: ["https://www.casamarbuzios.com/casamentos"],
    notes: "A página oficial informa mais de 10 anos de atuação e capacidade até 200 convidados; preço não publicado.",
  },
  {
    name: "Vila Capri Weddings",
    municipality: "Búzios",
    venueType: "Hotel e destination wedding",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    capacityMin: 20,
    capacityMax: 80,
    lodgingCapacity: 40,
    priceNote: "Referência de anúncio desde R$49.999; confirmar diretamente.",
    services: ["pacotes completos", "cerimônia", "recepção", "decoração personalizada", "buffet", "assessoria especializada", "hospedagem"],
    sourceUrls: ["https://www.casamentos.com.br/hotel-casamento/vila-capri-weddings--e480118"],
    notes: "Ficha do diretório atualizada em julho de 2026.",
  },
  {
    name: "Vila Massambaba",
    municipality: "Arraial do Cabo",
    venueType: "Bangalôs e celebrações",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    services: ["weddings", "celebrações", "bangalôs", "chef particular", "pratos regionais", "degustações", "jantares especiais", "vista panorâmica"],
    sourceUrls: ["https://vilamassambaba.com.br/"],
    contact: "(21) 96882-1961 · vilamassambaba@gmail.com",
    notes: "Capacidade e preço não publicados na página inicial.",
  },
  {
    name: "Casa de Festas Jardins",
    municipality: "Araruama",
    venueType: "Casa de festas e jardim",
    evidenceLevel: "OFFICIAL",
    status: "VALIDATED",
    capacityMax: 250,
    services: ["casamentos", "bodas", "15 anos", "340 m² cobertos", "1.200 m² de jardim", "decoração autoral", "buffet completo"],
    sourceUrls: ["https://www.casadefestasjardins.com.br/"],
    contact: "Rua São João, 359, Iguabinha, Araruama/RJ · (21) 99314-7887",
    notes: "O site informa operação desde 2015 e condições especiais de agenda para 2027.",
  },
  {
    name: "Doccas Gourmet",
    municipality: "São Pedro da Aldeia",
    venueType: "Restaurante e espaço intimista",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    capacityMax: 100,
    priceNote: "Card do diretório indica menus desde R$80 e 40–150 convidados; confirmar divergência.",
    services: ["casamentos", "salão para 60 pessoas", "área externa para 100 pessoas", "jardim", "menus personalizados", "massas", "carnes", "frutos do mar"],
    sourceUrls: ["https://www.casamentos.com.br/restaurante-casamento/doccas-gourmet--e218382"],
    notes: "O texto descritivo e o card do diretório apresentam capacidades diferentes; requer confirmação.",
  },
  {
    name: "Solarium Eventos",
    municipality: "São Pedro da Aldeia",
    venueType: "Salão à beira da Lagoa de Araruama",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    priceNote: "Referência de anúncio desde R$3.600 e mínimo de 10 convidados; confirmar diretamente.",
    services: ["casamentos", "jardins", "área verde de aproximadamente 500 m²", "cerimônia religiosa", "cozinha para buffet", "pista de dança", "estacionamento"],
    sourceUrls: ["https://www.casamentos.com.br/salao-casamento/solarium-eventos--e133131"],
    notes: "Ficha atualizada em agosto de 2026; serviços terceirizados com opções variadas.",
  },
  {
    name: "Space Hall",
    municipality: "São Pedro da Aldeia",
    venueType: "Salão de eventos",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    capacityMax: 800,
    priceNote: "Referência de anúncio desde R$7.500; confirmar diretamente.",
    services: ["salões integrados", "área externa para até 300 pessoas", "churrasqueira", "sauna", "cozinha para buffet", "estacionamento"],
    sourceUrls: ["https://www.casamentos.com.br/salao-casamento/space--e179177"],
    notes: "A ficha informa até 800 convidados sentados nos salões integrados.",
  },
  {
    name: "Buxixo Festas",
    municipality: "São Pedro da Aldeia",
    venueType: "Salão de festas e buffet",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    services: ["casamentos", "salão neutro", "decoração", "equipe de decoradores", "buffet"],
    sourceUrls: ["https://www.casamentos.com.br/salao-casamento/buxixo-festas--e179179"],
    notes: "Capacidade, preço e endereço detalhado não publicados na ficha aberta.",
  },
  {
    name: "Sítio Gratidão Festas e Eventos",
    municipality: "Saquarema",
    venueType: "Sítio arborizado",
    evidenceLevel: "DIRECTORY",
    status: "VALIDATED",
    priceNote: "Snippet de busca indicou menu desde R$4.500, mas o valor não apareceu no corpo da ficha; confirmar.",
    services: ["casamentos", "festas", "eventos", "ambientes integrados à natureza"],
    sourceUrls: ["https://www.casamentos.com.br/sitio-casamento/sitio-gratidao-festas-e-eventos--e325730", "https://www.instagram.com/sitiogratidao/"],
    notes: "Ficha identifica Saquarema e avaliação 5,0/5 baseada em duas opiniões.",
  },
  {
    name: "Amaré Espaço de Eventos",
    municipality: "Cabo Frio",
    venueType: "Espaço de eventos",
    evidenceLevel: "SOCIAL_LEAD",
    status: "REQUIRES_CONFIRMATION",
    capacityMin: 50,
    capacityMax: 200,
    priceNote: "Referência de anúncio desde R$5.000; confirmar.",
    services: ["casamentos", "eventos sociais", "espaço de recepção"],
    sourceUrls: ["https://www.casamentos.com.br/casa-para-casamento/amare-espaco-de-eventos--e476528", "https://www.instagram.com/amare.espacodeeventos/"],
    contact: "Rua Peixe Voador, 13, Ogiva, Cabo Frio/RJ · (22) 99931-5337",
    notes: "Classificado como lead por depender de confirmação comercial atual.",
  },
  {
    name: "Casa Rústica Festas e Eventos",
    municipality: "São Pedro da Aldeia",
    venueType: "Casa de festas",
    evidenceLevel: "SOCIAL_LEAD",
    status: "REQUIRES_CONFIRMATION",
    services: ["casamentos", "15 anos", "eventos corporativos", "aniversários", "possibilidade de acomodação"],
    sourceUrls: ["https://www.instagram.com/casarusticafestas/"],
    notes: "Lead de rede social; confirmar endereço, capacidade e disponibilidade.",
  },
  {
    name: "Vila Palace",
    municipality: "Saquarema",
    venueType: "Casa de festas",
    evidenceLevel: "SOCIAL_LEAD",
    status: "REQUIRES_CONFIRMATION",
    services: ["casamentos", "formaturas", "aniversários", "eventos corporativos"],
    sourceUrls: ["https://www.instagram.com/casadefestasvilapalace/"],
    notes: "Lead de rede social; confirmar endereço e estrutura.",
  },
  {
    name: "Recanto Du Correia",
    municipality: "Iguaba Grande",
    venueType: "Espaço para eventos",
    evidenceLevel: "SOCIAL_LEAD",
    status: "REQUIRES_CONFIRMATION",
    services: ["casamentos", "aniversários", "formaturas", "eventos corporativos", "natureza"],
    sourceUrls: ["https://www.instagram.com/recantoducorreia/"],
    notes: "Lead de rede social; confirmar capacidade, endereço e condições.",
  },
  {
    name: "Espaço Crystal Iguaba",
    municipality: "Iguaba Grande",
    venueType: "Espaço de festas",
    evidenceLevel: "SOCIAL_LEAD",
    status: "REQUIRES_CONFIRMATION",
    services: ["casamentos", "aniversários", "eventos corporativos", "ambiente arborizado", "piscina"],
    sourceUrls: ["https://www.instagram.com/espaco_crystal/"],
    notes: "Lead de rede social; confirmar disponibilidade e dados comerciais.",
  },
];
